### ISSUE TITLE
decode functions PER

### ISSUE THREAD

**Issue by ezor1** [eerimoq/asn1tools#1]
Dear eerimoq,

I'd like to use your tool for PER encoding/decoding. Do you know when the corresponding functions will be implemented? 
Are you still working on it? 

Thanks in advance

**Comment by eerimoq** [comment]
Hello!

asn1tool is a side project of mine that doesn't have any planning or schedule. Features are added whenever I find the project interesting, and a user request for additional functionality is certainly a good motivator. I wont promise anything, but I might have a look at it soon.

Is there any particular feature (as in ASN1 type) that you need?

**Comment by ezor1** [comment]
Thanks for your answer. 
I've tryed to do it by myself but I can't work out how functions works (I'm quite new in Python) 
However I could probably find out a solution if you implement one of them (let say the class Enumerate in per.py file for instance). Of course it's up to you. 
Anyway, I don't want to be rude by putting pressure on you. 

Thanks again,

Regards,

**Comment by eerimoq** [comment]
There are already a few functions implemented in https://github.com/eerimoq/asn1tools/blob/master/asn1tools/codecs/per.py with tests in https://github.com/eerimoq/asn1tools/blob/master/tests/test_per.py.

**Comment by eerimoq** [comment]
I implemented decode of the enumerated type in per.py. Not very well tested, but might work =)

**Comment by ezor1** [comment]
Many thanks errimoq. I'll try to use it and let you know if I find anything wrong (even if I'm sure it would work perfectly !)

**Comment by ezor1** [comment]
Hi,
Could you tell me wether the PER codec is the aligned or unaligned version?

**Comment by eerimoq** [comment]
It's aligned PER. Unaligned PER may be implemented eventually, but first I'll focus on aligned PER.

**Comment by eerimoq** [comment]
Okay, I couldn't resist, I started on the UPER codec as well.

See https://github.com/eerimoq/asn1tools/blob/master/tests/test_uper.py for tests.

**Comment by eerimoq** [comment]
The UPER decoder now successfully decodes a couple of ASN.1 types; SEQUENCE, CHOICE, BIT STRING, OCTET STRING, ENUMERATION and INTEGER. The implementation is by no means complete, but should generally work good.

Would be nice if you can create a pull request with one or more test cases of your ASN.1 specification. That would ensure that your types and be encoded and decoded. Add test cases in https://github.com/eerimoq/asn1tools/blob/master/tests/test_uper.py.

**Comment by ezor1** [comment]
I'll see what I can do

**Comment by ezor1** [comment]
Dear Eerimoq,

I've push a very simple script to test multiple modules case (I'll try to make something more comprehensive soon). It seems that it doesn't work and stop compiling at the end of the first module encounter. 
Maybe it will be better to allow compile_file to use as first argument a list of files, each one containing a module and store all of them temporarily to deals with dependencies (IMPORTS/EXPORT types).

The others tests I've performed on all types let me think your tools does the job pretty well though ;)

**Comment by eerimoq** [comment]
Hello,

I think it's a good idea to accept either a single file or a list of files as first argument of `compile_file()`. It's probably a common use case.

I think the pull request (PR) includes your latest changes. I'll make a code review of the PR and eventually merge it.

**Comment by ezor1** [comment]
I'll make another PR to improve `compile_file`.

**Comment by eerimoq** [comment]
I already implemented compile_file() to allow one or more files. I also renamed the function to compile_files(). :)

**Comment by eerimoq** [comment]
Okay, I merged the first PR and styled the code to my liking. Anything else, or should we close this issue and open new issues if there are other features missing?
