### ISSUE TITLE
Performance impact of adding Error location information

### ISSUE THREAD

**Issue by Finndersen** [eerimoq/asn1tools#132]
As part of some of the changes I have made to error handling in ASN1tools, I made some improvements to how the location of a Decode/Encode error is detected & displayed.
This was done by creating a decorator to decorate any methods which may raise a Decode/Encode error, catches the error and adds the name of the element to the location in the exception object:

```
def add_error_location(method):
    """
    Method decorator which catches ErrorWithLocation subclasses and adds element name to location
    If decorator is applied to parent Type class method, this functionality can be disabled on a per-child
    Type basis by setting no_error_location=True
    :param method:
    :return:
    """
    @wraps(method)
    def new_method(self, *args, **kwargs):
        try:
            return method(self, *args, **kwargs)
        except ErrorWithLocation as e:
            # Don't add name if it is blank (for SEQUENCE OF, SET OF etc)
            if self.name and not getattr(self, 'no_error_location', False):
                e.add_location(self.name)
            raise e
    return new_method
```

```
class Any(Type):

    def __init__(self, name):
        super(Any, self).__init__(name, 'ANY', None)

    @add_error_location
    def encode(self, data, encoded):
        encoded.extend(data)

    @add_error_location
    def decode(self, data, offset, values=None):
        start = offset
        offset = skip_tag(data, offset)
        length, offset = decode_length_definite(data, offset)
        end_offset = offset + length

        return data[start:end_offset], end_offset
```

However with profiling I have realised that even the basic new_method() wrapper (which does nothing but call underlying method when no exception occurs) introduces a notable performance overhead, simply because it is called so often:
![image](https://user-images.githubusercontent.com/17341337/141235900-d1a828a4-81aa-4f62-a0a6-270ca9e08ddf.png)

There is a worthwhile performance improvement when it is removed (over 30% reduction in processing time in some cases):
![image](https://user-images.githubusercontent.com/17341337/141235964-9575d65a-949f-436c-9f35-52bc4710b75a.png)

It would be good to improve this and am hoping to get some feedback on how to do so. Some options:

- Remove entirely and do not add Exception location information (probably not ideal)
- Some other implementation (would be very messy to add try/except block to every method that does decoding/encoding, there are a lot)
- Some mechanism for user to set option to enable detailed error location tracking for debugging purposes, but disabled during normal operation?
- Only apply to decode/encode methods of limited container types e.g. MembersType, which will add less detailed error location information but will be much more efficient 

I think the last option is a good middle-ground and will experiment with doing that, would appreciate any other feedback
Cheers
Finn

**Comment by eerimoq** [comment]
Sounds good. Performance is important. Python is slow by design, and we should do our best to write optimized code.

**Comment by Finndersen** [comment]
Addressed
