### ISSUE TITLE
XER crashes when it encounters odd-length string  while parsing OCTET STRING type

### ISSUE THREAD

**Issue by hurufu** [eerimoq/asn1tools#136]
Given ASN.1 module: [Test Module](https://raw.githubusercontent.com/hurufu/nexoid-protocol-collection/main/Scapi.asn1)
When this message is received `<ScapiNngNotification xmlns=""><ntf><events><manualEntry><pan>4485936516057131</pan><expirationDate><year>22</year><month>11</month></expirationDate><cvdData><cvd>111</cvd></cvdData></manualEntry></events></ntf><id>0</id></ScapiNngNotification>`
Then crash occurs.

I think it can be easily fixed in file `codecs/xer.py:313`
```
if len(element.text) % 2:
    return binascii.unhexlify(element.text.zfill(len(element.text)+1))
return binascii.unhexlify(element.text)
```

But I don't know if it is legal behavior according to the ASN.1 XER specification.

**Comment by eerimoq** [comment]
Feel free to take a look in the specification and submit a PR with a fix and I can merge. I don't know the specification very well myself unfortunately.

**Comment by hurufu** [comment]
I've checked the spec and it looks like this behavior isn't allowed.

X.693 tells:
> 9.4 Octetstring value
If the "XMLTypedValue" alternative of "XMLOctetStringValue" (see Rec. ITU-T X.680 | ISO/IEC 8824-1, 23.3) can
be used (as specified in Rec. ITU-T X.680 | ISO/IEC 8824-1, 23.4), then it shall be used. Otherwise, the "**xmlhstring**"
alternative shall be used with all "white-space" removed (see 8.3.4), and all letters in upper-case.

And consequently X.680 tells:
>23.8 If the "hstring" is an odd number of hexadecimal digits, it shall be interpreted as if it contained a single
additional trailing zero hexadecimal digit. The "xmlhstring" **shall not** be an odd number of hexadecimal digits.

The example APDU cant use XMLTypedValue for the value in question (`cvd`), so the only possibility is that it should be interpreted as xmlhstring. For which odd length strings are explicitly forbidden. Which is strange, because a well known compiler [asn1c](http://www.lionet.info/asn1c/) actually accepts such APDUs.

I will submit a PR in a free time, because it seems like a good idea to be liberal in what input the library can accept.
