### ISSUE TITLE
can xer.py CompileType dump XML tags for ASN definitions. 

### ISSUE THREAD

**Issue by mungayree** [eerimoq/asn1tools#15]
Is it possible to enhance the xer.py CompileType dump the XML tree w.r.t to any module ?
like say dumpxml() method which will print below asn as -

    PersonData-Module DEFINITIONS AUTOMATIC TAGS ::=
    BEGIN
    Person-Info ::= SEQUENCE {
        person-name   [0] IMPLICIT VisibleString (SIZE(0..64)),
        person-id  [1] IMPLICIT VisibleString (SIZE(16..36)),
        person-type     [2] IMPLICIT ENUMERATED {
            e-man(0),
            e-woman(1),
            e-boy(2),
            e-girl(3),
            ...
        },
        person-last-ids    [3] IMPLICIT SEQUENCE (SIZE(1..3)) OF OCTET STRING (SIZE(4..16)),
        ...
    }
    END

printed as below or similar  .....  if the same is printed in JSON it can be converted to XML

    <Person-Info>
        <person-name>VisibleString</person-name>
        <person-id>VisibleString</person-id>
        <person-type><e-man/></person-type>
        <person-last-ids>octect</person-last-ids>
    </Person-Info>

**Comment by eerimoq** [comment]
I'm not sure I understand what you mean. Please elaborate a bit on your description.

**Comment by mungayree** [comment]
Sorry, if being unclear on the requirements, but was finding if there is any converter like tool (asn to xml) or asn to JSON ?

**Comment by eerimoq** [comment]
Okay, so today the parser parses ASN.1 file(s) and converts them to a dictionary. For example, [foo.asn](https://github.com/eerimoq/asn1tools/blob/master/tests/files/foo.asn) is converted to [foo.py](https://github.com/eerimoq/asn1tools/blob/master/tests/files/foo.py). It is certainly possible to dump foo.py as XML or JSON, but there is no support for it today.

**Comment by eerimoq** [comment]
Will you implement it?

**Comment by mungayree** [comment]
Erik,

I saw you close the Issue. sorry was late in responding, but I am caught up
with some stuff around this and fail to have this bandwidth. i will try in
background and relay you the fixes or code.
This was a much need feature as asn1tools should be eventually able to make
JSON dictionaries/XML schema so USER can both encode using fields and use
the binary to INJECT.

Thanks
Parag Manjrekar

**Comment by eerimoq** [comment]
Okay, I don't quite understand what you mean by "INJECT", but I'm sure it's a good feature =)

**Comment by mungayree** [comment]
Majority of time in early phases; tester/developer would want to dump their ASN1 spec definitions to JSON/XML schema (preferably  JSON) and using this JSON schema they can quickly encode into substrate (or a binary blob).

The blob can be then INJECTED on any transports like RESTAPI  URL or even Ethernet.

**Comment by eerimoq** [comment]
What's the benefit of sharing the ASN.1 specification formatted as JSON or XML, compared to sharing the original specification?

ASN.1 specifications have an extensive grammar with lots of types, constraints, values, classes, etc. To be able to convert the original specification to JSON or XML one would need to define how to convert all possible grammar. Thats' easier said than done. It's certainly possible taking shortcuts, which would be the only way forward to have any progress at all in implementing such a feature.

**Comment by mungayree** [comment]
Erik,
your comment --
"Okay, today the parser parses ASN.1 file(s) and converts them to a dictionary. For example, foo.asn is converted to foo.py. It is certainly possible to dump foo.py as XML or JSON, but there is no support for it today."

Is this a utility/function. How do you convert foo.asn to foo.py?

**Comment by eerimoq** [comment]
It's an internal format taking shortcuts. It's meant to be a stable, well defined, format, but currently may change as new features requires more information. But yeah, a JSON dump could use that format. Should not be too hard to implement, I think.

**Comment by mungayree** [comment]
The use case for me is as follows -

I am testing against a engine which heavily uses ASN1 based BER payloads. After receiving the payloads it decodes data to modify it own database.  This ASN1 spec has almost 100 structures and tons of members in them. Some of the sequences are even optional.

Its currently getting too tedious to encode the exact members along with the intricate names.
A JSON representation of ASN1 had helped to quickly make jazzy data combination, bundle it (encode) and pump or inject it to this ASN1 engine and verify its return response using asn1tool.decode()

**Comment by eerimoq** [comment]
I have no plans on implementing this, but you're welcome to do so.
