### ISSUE TITLE
Unsupported type 'BIT STRING' error in generate C source uper

### ISSUE THREAD

**Issue by hiranshahi** [eerimoq/asn1tools#152]
`asn1tools generate_c_source --codec uper --namespace uper tests/files/c_source/c_source.asn`
Hi,
above command does not work for me and I get the following error:

`error: CRef.AT: Unsupported type 'BIT STRING'.`

**Comment by eerimoq** [comment]
Which version are you using? Maybe a new release should be published to PyPI with the support for BIT STRING?

**Comment by Futsch1** [comment]
This was just fixed in #149. I have created a new tag v0.163.0 which should be available in pypi soon.

**Comment by hiranshahi** [comment]
> 

I was using version 0.161.0.
After upgrading to version 0.162.0 (which I downloaded from github) my problem was solved.
Thank you
