### ISSUE TITLE
Decode successfully ignores extra bytes

### ISSUE THREAD

**Issue by thobiaskarlsson** [eerimoq/asn1tools#162]
Hi!

When decoding an ASN.1 message with e.g. some crap bytes at the end, the lib silently (and successfully) decodes the message and simply ignores the extra bytes. 

Due to this not being as strict as we'd like, we currently do a round-trip decode-encode and verify that the re-encoded bytes matches the input. This is somewhat cumbersome. Would it be possible to get a flag (or similar) that would fail the decoding process if not all bytes were being used during decoding?

**Comment by Finndersen** [comment]
A faster way to verify would be to use decode_with_length() to get the number of bytes used and compare to total byte size of the file

**Comment by thobiaskarlsson** [comment]
Oh thank you! We will try it out. :+1:
