### ISSUE TITLE
Type 'SetupRelease' not found in module 'EUTRA-RRC-Definitions'.

### ISSUE THREAD

**Issue by anheiqishi25** [eerimoq/asn1tools#184]
[lte-rrc-16.13.0.txt](https://github.com/user-attachments/files/16071389/lte-rrc-16.13.0.txt)
SetupRelease is a parameterization type in the module "EUTRA-RRC-Definitions",
When I compile the above file with the command asn1tools.compile_files(filenames=filename, codec='per'), it prompts: 

'''   Type  'SetupRelease' not found in module 'EUTRA-RRC-Definitions'.   '''

Can someone help answer my questions?
Thank you very much.

**Comment by PsArzzz** [comment]
Hello, may I ask how you solved this problem?
