### ISSUE TITLE
Length determinant type 0xff not yet supported.

### ISSUE THREAD

**Issue by bandzaw** [eerimoq/asn1tools#21]
Tried to convert my uper based data to json using:
```asn1tools convert -i uper -o jer``` but asn1tools complained that:
```error: Length determinant type 0xff not yet supported.```

**Comment by eerimoq** [comment]
There are a few features missing in the UPER codec, and you found one of them. It would be helpful if you can provide your ASN.1 specification/schema and the data to decode, and I can have a look at it and hopefully implement the missing feature.

**Comment by eerimoq** [comment]
Btw, `0xff` is an invalid length determinant. Either your data is corrupt, or there is a bug in asn1tools. I modified the code to print a more detailed error message.

Please update to asn1tools version 0.77.0 (`pip install -U asn1tools`) and answer with the new error message.

**Comment by bandzaw** [comment]
It is very possible my data was corrupt (my data hexdump utility had a bug). Using version 0.78 with correct data successfully allowed me to convert that data to json. Thanks.
