### ISSUE TITLE
struct.error: required argument is not an integer

### ISSUE THREAD

**Issue by Bujko** [eerimoq/asn1tools#27]
Hi!

Trying to run the following code but I got the following error.

```
File "EnrolementCredential.py", line 49, in <module>
    'signature' : ('ecdsaNistP256Signature', { 'r' : ('x-only' , xstr2_EC), 's' : ystr2_EC})
struct.error: required argument is not an integer
```

I got the same error if I delete the optional signature value (the last row in my code down below).
I used the same values by pyasn1 but should change because of the COER encoding. 

This is the ASN.1 implementation

```
ToBeSignedCertificate ::=
        SEQUENCE {  id                      CertificateId,
                    cracaId                 HashedId3,
                    crlSeries               CrlSeries,
                    validityPeriod          ValidityPeriod,
                    region                  GeographicRegion OPTIONAL,
                    assuranceLevel          SubjectAssurance OPTIONAL,
                    appPermissions          SequenceOfPsidSsp OPTIONAL,
                    certIssuePermissions    SequenceOfPsidGroupPermissions OPTIONAL,
                    certRequestPermissions  SequenceOfPsidGroupPermissions OPTIONAL,
                    canRequestRollover      NULL OPTIONAL,
                    encryptionKey           PublicEncryptionKey OPTIONAL,
                    verifyKeyIndicator      VerificationKeyIndicator,
                    ...
}
```

This is my code:

``` python
#EneolementCredential

import asn1tools
import datetime, calendar, time
from Crypto.PublicKey import ECC

issuerid  = bytes.fromhex('0101010101010101') #Example value
cracaId   = bytes.fromhex('020202') # Identifies the Certificate Revocation Authorization CA (example)
crlSeries = 5 #Example value

t = (2004, 1, 1, 0, 0, 0, 3, 1, 0) # TAI time type secs from this moment
generation_time = calendar.timegm(time.gmtime())-time.mktime(t)
#duration
duration_type = 'hours' # My choice
in_hours      = 8761 #One year (example)


f = open('myprivatekey.der','rb')
EC_key = ECC.import_key(f.read())
f.close()

x_EC = EC_key.pointQ.x  # x and y key point conversation
y_EC = EC_key.pointQ.y

xstr1_EC = str(hex(int(x_EC)))
xstr2_EC = bytes.fromhex(xstr1_EC[2:66])
ystr1_EC = str(hex(int(y_EC)))
ystr2_EC = bytes.fromhex(ystr1_EC[2:66])

xstr2_EC = b'0808080808080808080808080808080808080808080808080808080808080808'
ystr2_EC = b'0808080808080808080808080808080808080808080808080808080808080808'

Certificate = asn1tools.compile_files('EtsiTs102941MessagesItss.asn',codec='oer')

encoded = Certificate.encode('CertificateBase',{
                                                'version'   : 3,
                                                'type'      : 'explicit',
                                                'issuer'    : ('sha256AndDigest', issuerid),
                                                'toBeSigned':   {
                                                                    'id'                : ('none', ''), #Possibly none
                                                                    'cracaId'           : cracaId,
                                                                    'crlSeries'         : crlSeries,
                                                                    'validityPeriod'    :   {
                                                                                                'start'     : generation_time,
                                                                                                'duration'  : (duration_type, in_hours)
                                                                                            },
                                                                    'verifyKeyIndicator': ('verificationKey' , ('ecdsaNistP256' , ('uncompressed', {'x' : xstr2_EC  , 'y' : ystr2_EC})))
                                                                },
                                                'signature' : ('ecdsaNistP256Signature', { 'r' : ('x-only' , xstr2_EC), 's' : ystr2_EC})
                                               }
                            )
```

Using the ASN.1 code of the [Ieee1609.2 standard](https://zapdf.com/ieee-standard-for-wireless-access-in-vehicular-environmentscf4b57e59eec334c6c843163225bbd1799754.html)

I am newbie at ASN.1. I do something wrong or something else is the problem? The COER encoding or the '...' part could be the problem?

**Comment by eerimoq** [comment]
Please attach `EtsiTs102941MessagesItss.asn` to make it possible to easily reproduce the issue.

**Comment by Bujko** [comment]
Here it is with the key included.


[Issue.zip](https://github.com/eerimoq/asn1tools/files/2138193/Issue.zip)

**Comment by eerimoq** [comment]
The problem is that a floating point number is not allowed encoding an integer. Replace `generation_time = calendar.timegm(time.gmtime())-time.mktime(t)` with `generation_time = int(calendar.timegm(time.gmtime())-time.mktime(t))` and the example works.

**Comment by eerimoq** [comment]
The syntax in this specification is unlike anything I've seen before. I'll do my best adding support for the missing functionality.

**Comment by Bujko** [comment]
Thank you so much for the fast response. It is working correctli.

**Comment by eerimoq** [comment]
Do you have the unmodified ASN.1-specification as well? I could use it as a test case when inplementing support for more ASN.1 syntax.

**Comment by Bujko** [comment]
Here are the files.

With pyasn1 I can not use this definitions (it failed on "WITH COMPONENTS" and some other specific parts). Also the import export part is not working. With pyasn1 and I could not figure out how can I do this with your library.

Hope that it is helping you and I cut of every modifications. 
I think that the EtsiTs103097 and the Ieee files will be enough because the EtsiTs102941 asn file includes more than one asn1 architecture.

I am working with the Ieee 1609.2 (2016)  and the EtsiTs103097 v 1.3.1 standards.

These defines COER encoding.

I have try to find out, based on the documentation, that what kind of OER do you use.
Is it BASIC or CANONICAL OER?

If I can help you with anything let me know about it.


[Iee1609dot2_asn1_files.zip](https://github.com/eerimoq/asn1tools/files/2138454/Iee1609dot2_asn1_files.zip)

**Comment by Bujko** [comment]
I have created IEEE 1609dot2 certificate and I passed it to a java code. It seems to be correct COER encoded.

**Comment by eerimoq** [comment]
I fixed a bug not allowing `EXPORTS ALL;`, and added support for types in constraints. Now only a few manual modifications have to be done to make [IEEE 1609dot2](https://github.com/eerimoq/asn1tools/blob/master/tests/files/ieee/ieee1609_2.asn) compile.

Replace [this section](https://github.com/eerimoq/asn1tools/blob/master/tests/files/ieee/ieee1609_2.asn#L458-L478) with:

``` asn1
NinetyDegreeInt ::= INTEGER {
    min (-900000000),
    max (900000000),
    unknown (900000001)
} (-900000000..900000001)

KnownLatitude ::= NinetyDegreeInt (-900000000..900000000)

UnknownLatitude ::= NinetyDegreeInt (900000001) -- Minus 90 deg to +90
                                              -- deg in microdegree
                                              -- intervals

OneEightyDegreeInt ::= INTEGER {
    min (-1799999999),
    max (1800000000),
    unknown (1800000001)
} (-1799999999..1800000001)

KnownLongitude ::= OneEightyDegreeInt (-1799999999..1800000000)

UnknownLongitude ::= OneEightyDegreeInt (1800000001)
```

Here is a test that does similar encoding as in your example: https://github.com/eerimoq/asn1tools/blob/master/tests/test_oer.py#L685-L751
