### ISSUE TITLE
Value error: time data '201801221329' does not match format '%Y%m%H%M%S.%f'

### ISSUE THREAD

**Issue by rowlandAtGitHub** [eerimoq/asn1tools#28]
Was getting this message

`Value error: time data '201801221329' does not match format '%Y%m%H%M%S.%f'`

 when running some asn1 through a python program using asn1tools.
Part of the traceback was `"~/site-packages/asn1tools/codecs/__init__.py", line 220, in generalized_time_to_datetime`, so I amended the if else to include a test for string length of 13
and `date = datetime.strptime([string[:-1], '%Y%m%H%M')`

This worked.

This was happening because the timestamp was exactly on the minute, and so did not include seconds.

**Comment by rowlandAtGitHub** [comment]
I am using codec G711

**Comment by eerimoq** [comment]
BER, DER, PER, JER, XER?

**Comment by rowlandAtGitHub** [comment]
Sorry codec is BER

**Comment by eerimoq** [comment]
A fix is part of version 0.123.1, available on PyPI.

Enjoy!

**Comment by eerimoq** [comment]
Let me know if it works or not.

**Comment by rowlandAtGitHub** [comment]
Yes it works. I don't get the error now. Thanks very much.
