### ISSUE TITLE
How to use parse_files for filling the values of the keys in the dictionary

### ISSUE THREAD

**Issue by ashwin2701** [eerimoq/asn1tools#29]
My requirement is to create a dictionary based on the asn file and then fill the key's value using an excel sheet, and then later encode/decode .Currently I'm manually creating the desired output and filling its values from the excel sheet, Now for the below schema, Is the Parsed output and desired output both same?if both are same how do we fill values for the keys inside a dictionary? If not how to make the parser output equivalent to desired output?Any recommendations would be highly helpful.

Module-order DEFINITIONS AUTOMATIC TAGS ::=

BEGIN

Order ::= SEQUENCE {

header Order-header

}

Order-header ::= SEQUENCE {

reference NumericString (SIZE (12)),

date NumericString (SIZE (8)) -- MMDDYYYY --

}END

Parser Output

            foo = asn1tools.parse_files('we.asn')

            foo

{'Module-order': {'extensibility-implied': False, 'tags': 'AUTOMATIC', 'imports': {}, 'object-sets': {}, 'values': {}, 'object-classes': {}, 'types': {'Order': {'type': 'SEQUENCE', 'members': [{'type': 'Order-header', 'name': 'header'}]}, 'Order-header': {'type': 'SEQUENCE', 'members': [{'type': 'NumericString', 'name': 'reference', 'size': [12]}, {'type': 'NumericString', 'name': 'date', 'size': [8]}]}}}}

{header:{reference:NumericString (SIZE (12)),date NumericString (SIZE (8)) -- MMDDYYYY --}}

Desired Output

{'header':{'reference': NumericString,'date':NumericString}}

**Comment by eerimoq** [comment]
Sorry, but I think transforming one dictionary to another is out of scope for this project.

**Comment by ashwin2701** [comment]
So for encoding or decoding we have to pass some integer or string value to dictionaries which we create right,how it is done

**Comment by eerimoq** [comment]
You have to be more specific. It's impossible to understand what you want to achieve.

**Comment by ashwin2701** [comment]
Parse_files function will create a dictionary which will have members and type of members may be string or integer ,Now with respect to my understanding for encoding or decoding to happen we give the members with value of 1,2 etc which integer datatype,So my question was that  is there way to give values to the members

**Comment by ashwin2701** [comment]
Ok it looks like you encoding/decoding without giving any values to the members of the dictionary.

**Comment by ashwin2701** [comment]
I'm not sure where you are asking me to look,for the parser_files created dictionary how can I feed string value for member reference and date.

**Comment by eerimoq** [comment]
I still don't understand what you want to achieve, sorry.

**Comment by ashwin2701** [comment]
How can we assign values to the members of the dictionary which is your module is creating.

**Comment by ashwin2701** [comment]
Can the value for the members be assigned through the program itself.

**Comment by ashwin2701** [comment]
>>> import asn1tools
>>> foo = asn1tools.compile_files('tests/files/foo.asn')
>>> encoded = foo.encode('Question', {'id': 1, 'question': 'Is 1+1=3?'})
>>> encoded
bytearray(b'0\x0e\x02\x01\x01\x16\x09Is 1+1=3?')
>>> foo.decode('Question', encoded)
{'id': 1, 'question': 'Is 1+1=3?'} 

Now it looks OK since there are only two members inside Question schema but consider a scenario where i need to assign value for member3 with value 4 which is under  schema of schema of schema.Then to encode you need to do something like this

encoded = foo.encode('Random', {'member1': {member2:{member3:4}}}) 

 Is there a way where  you give value for member3=4 and it itself creates the dictionary of dictionaries format for encoding based on hierarchy got from  asn1tools.parse_files('tests/files/foo.asn')

**Comment by eerimoq** [comment]
No, there is no support in asn1tools for using the dictionary created by ``parse_files()`` to generate dictionaries with data to encode with ``foo.encode()``. Why do you need that?

**Comment by ashwin2701** [comment]
Ok currently I have to handle schema whose  members  may be again schemas which might extrend upto n levels,Now my task is to create a dictionary of dictionaries for any schema,and value for its members  i will fill through an excel sheet, and then later use that dictionary for encoding .I was confused whether I can utilize your asn1tools.parse_files('tests/files/foo.asn') which is returning a dictionary showing the hierarchy of parent dictionary and its child members, and then utilize that hierarchy to fill the values to create the dictionary needed for encoding.

**Comment by eerimoq** [comment]
Ok, as that functionality is not supported I suggest closing this issue.
