### ISSUE TITLE
compatible with marben

### ISSUE THREAD

**Issue by xusunny** [eerimoq/asn1tools#31]
Hello，do you know whether asn1tool is compatible with marben, if don't, how to make asn1tool can decode bytearray which is generated by marben?

**Comment by xusunny** [comment]
I decode bin file which is encoded by marben, the decode result is not consistent， we use the same asn files，can you help me check?

**Comment by eerimoq** [comment]
asn1tools should be compatible with Marben. If it isn't there is a bug in one or both of the tools.

Please give an example where the two tools are incompatible.

**Comment by xusunny** [comment]
below bytes is per encoded result of Objective Systems.INC , not marben...

b'\xfc(\xe0[\x95\xe8\x0c\x01C\xe0[\x95\xe8\x0c\x01C \x02\xd08\x003\x00\x81\xa1\x07\xb8\x86{\xb22\xc0\x99\xca\xef\xb8\x02\r\x00\x03\x00\xff\xff\x00\x00 \x00\x01\x00\x07\xf8\x03H\x01\x006\xe0460024965507250\x98898602C9991630067250\x044G\x0c2608009204F3\x0f864090033197720\x111.0.0B06_V1.0E.50\x00'

and the origin data is 

Data {   
header {     
requestid = 40      
timeStamp {         seconds = 1536550924         milliseconds = 323      }      
eventId {         seconds = 1536550924         milliseconds = 323      }      
creatorId = ecu      
messageTTL = 720      
requestType = serviceRequest      
ackRequired = FALSE   }   
body {      
serviceId = rvs     
 serviceData {         
vehicleStatus {            
basicVehicleStatus {               
position {                  
latitude = 108769842                  
longitude = 432730040                 
 altitude = 425                  
posCanBeTrusted = FALSE                  
marsCoordinates = FALSE               }              
speed = 65535               
direction = 0            }            
additionalVehicleStatus {               
maintenanceStatus {                  
daysToService = 1890               }            }           
 temStatus {              
 powerSource = mainBattery               
powerMode = normal               
networkAccessStatus {                 
 simInfo {                     
imsi = '460024965507250'                    
 iccId = '898602C9991630067250'                  }                  
mobileNetwork = '4G'               }              
 serialNumber = '2608009204F3'               
imei = '864090033197720'               
mpuVersion = '1.0.0B06_V1.0E.50'           
 }        
 }     
 }      
seq = 0   }}

I decode it with asn1tool,  the result is 

{
   "body": {
      "serviceId": 1976
   },
   "header": {
      "ackRequired": false,
      "requestType": "ack",
      "creatorId": "ecu",
      "eventId": {
         "milliseconds": 51,
         "seconds": 3379087532019768
      },
      "timeStamp": {
         "milliseconds": 23445,
         "seconds": 25779046747030496
      },
      "messageTTL": 129,
      "requestid": 40
   }
}

these two dict-like data are not consistent,  
 "basicVehicleStatus" is not been decode,
and "seconds" has the wrong value.
thank you very much if you can help me.

**Comment by eerimoq** [comment]
Attach the ASN.1 schema.

**Comment by xusunny** [comment]
I found difference between encoding result with asn1tool and Objective Systems.Inc, I offer what you need ,  I will be greatly appreciated if you help me resolve it, thank you!

the python script:
class AsnMqtt(object):

    def __init__(self):
        pass

    @classmethod
    def get_asn_mqtt(cls):
        if not hasattr(AsnMqtt, 'biz_asn_mqtt'):
            asn_path = __file__[0:__file__.index('mqtt_proc')] + 'Config/asn1_mqtt_b/'
            compile_files = []
            fs = os.listdir(asn_path)
            for fl in fs:
                compile_files.append(asn_path + fl)
            AsnMqtt.biz_asn_mqtt = asn1tools.compile_files(compile_files, codec='per')
        return AsnMqtt.biz_asn_mqtt


if __name__ == '__main__':
    biz_asn_mqtt = AsnMqtt.get_asn_mqtt()
    file_name = 'D:\GeelyTester\OBSEngine\Config\\testcases\\message.dat '
    # read and print bytes of message.dat
    with open(file_name, mode='rb') as fr:
        value = fr.read()
        print(value)
    # decode message.dat
    decode_result = biz_asn_mqtt.decode('VDServiceRequest', value)
    import json
    print(json.dumps(decode_result, indent=3))
    # encode the decode result
    encode_data = biz_asn_mqtt.encode('VDServiceRequest', decode_result)
    print(encode_data)
    # encode origin dict which was used to generate message.dat
    timestamp = {'seconds': 1536550924, 'milliseconds': 323}
    request_header = {'requestid': 40,
                      'timeStamp': timestamp,
                      'eventId': timestamp,
                      'creatorId': 'ecu',
                      'messageTTL': 720,
                      'requestType': 'serviceRequest',
                      'ackRequired': False
                      }
    Position = {'latitude': 108769842,
                'longitude': 432730040,
                'altitude': 425,
                'posCanBeTrusted': False,
                'marsCoordinates': False
                }
    BasicVehicleStatus = {'position': Position,
                          'speed': 65535,
                          'direction': 0
                          }
    MaintenanceStatus = {'daysToService': 1890}
    SIMInfo = {'imsi': '460024965507250',
               'iccId': '898602C9991630067250'
               }
    NetworkAccessStatus = {'simInfo': SIMInfo,
                           'mobileNetwork': '4G'}
    TemStatus = {'powerSource': 0,
                 'powerMode': 'normal',
                 'networkAccessStatus': NetworkAccessStatus,
                 'serialNumber': '2608009204F3',
                 'imei': '864090033197720',
                 'mpuVersion': '1.0.0B06-V1.0E.50'
                 }
    AdditionalVehicleStatus = {'maintenanceStatus': MaintenanceStatus}
    VehicleStatus = {'basicVehicleStatus': BasicVehicleStatus,
                     'additionalVehicleStatus': AdditionalVehicleStatus,
                     'temStatus': TemStatus}
    ServiceData = {'vehicleStatus': VehicleStatus}
    body = {
        'serviceId': 51,
        'serviceData': ServiceData,
        'seq': 0
    }
    payload = {'header': request_header,
                     'body': body}
   # encode payload
    encode_data = biz_asn_mqtt.encode('VDServiceRequest', payload)
    print(encode_data)

relating with payload,  encode result of asn1tool is 

b'\xfc(\xb0[\x95\xe8\x0c\x01C\xb0[\x95\xe8\x0c\x01C \x02\xd08\x003\x00\x81\xa1\x07\xac\x86{\xb22`\x99\xca\xef\xb8\x02\r\x00\x03\x00\xff\xff\x00\x00 \x00\x01\x00\x07\xf8\x03H\x01\x006\xe0460024965507250\x98898602C9991630067250\x044G\x0c2608009204F3\x0f864090033197720\x111.0.0B06-V1.0E.50\x00'
--
encode result of Objective Systems.INC is 

b'\xfc(\xe0[\x95\xe8\x0c\x01C\xe0[\x95\xe8\x0c\x01C \x02\xd08\x003\x00\x81\xa1\x07\xb8\x86{\xb22\xc0\x99\xca\xef\xb8\x02\r\x00\x03\x00\xff\xff\x00\x00 \x00\x01\x00\x07\xf8\x03H\x01\x006\xe0460024965507250\x98898602C9991630067250\x044G\x0c2608009204F3\x0f864090033197720\x111.0.0B06_V1.0E.50\x00'
--

and asn1 schema is 
VDS_CORE DEFINITIONS AUTOMATIC TAGS ::= BEGIN

VDServiceRequest ::= SEQUENCE {
	header 	RequestHeader, -- A request header, common for all requests
	body 	RequestBody OPTIONAL -- A request body specific for the type of service being executed
}

RequestHeader ::= SEQUENCE {
	requestid 			RequestId, -- An identifier of this request, must be unique to the sending party. If this request is an ACK, this is the identifier of the request being acknowledged
	timeStamp			TimeStamp, -- The time when this message was created
	eventId 			TimeStamp OPTIONAL, -- Identifier of the service event that is being executed, the value is the time when the event is created
	creatorId			CreatorId OPTIONAL, -- Identifies if this event was created by a TEM unit or CVC back-end
	messageTTL			MessageTTL OPTIONAL, -- Message time-to-live after which this request message should be discarded, no present means no limit
	requestType			RequestType OPTIONAL,-- Identifies the type of message, no presents means serviceRequest
	ackRequired			ACKRequired OPTIONAL-- If this request needs to be acknowledged, no present means false
}

RequestId ::= INTEGER (0..255)


TimeStamp ::= SEQUENCE {
  seconds INTEGER(0..2147483647),  -- UTC Timestamp
  milliseconds  INTEGER(0..999) OPTIONAL -- Millisecond within the second
}


CreatorId ::= ENUMERATED {
	ecu		(0),
	cvc		(1)
}

MessageTTL ::= INTEGER(0..86400)  -- Time in 10s increment (240 hours). 0=Unlimited TTL

RequestType ::= ENUMERATED{
	serviceRequest		(0),
	ack     			(1)
}

ACKRequired ::= BOOLEAN

RequestBody ::= SEQUENCE {
  serviceId 			ServiceId OPTIONAL, -- Determines the service that is being executed (defined in service specific ASN.1 file)
  serviceData 			ServiceData OPTIONAL, -- Service specific data (defined in service specific ASN.1 file)
  seq                   MessageSequence OPTIONAL -- Message sequence to prevent the replay attack
}

MessageSequence ::= INTEGER (0..255)

ServiceId ::= INTEGER{
	svt (41), -- SVT
	stn (44), -- Theft Notification
	rvs (51), -- Remote status & dashboard
}(0..17575)

ServiceData ::= SEQUENCE {
	vehicleStatus           VehicleStatus  OPTIONAL,	-- defined in specific device status ASN.1 file)
}

BasicVehicleStatus ::=SEQUENCE {
    position            Position ,
    speed               INTEGER , -- km/h   
	speedValidity		INTEGER (0..1) OPTIONAL, -- 0x0: valid, 0x1: Invalid
	direction           INTEGER (0..360) OPTIONAL,
}

AdditionalVehicleStatus ::=SEQUENCE {
  maintenanceStatus           MaintenanceStatus   OPTIONAL,
}

TEMStatus ::= SEQUENCE {
	powerSource               PowerSource,
	powerMode                 TEMPowerMode,  
	networkAccessStatus       NetworkAccessStatus OPTIONAL, -- the network access information
	serialNumber              PrintableString OPTIONAL,
	imei                      PrintableString OPTIONAL,
	mpuVersion                PrintableString  OPTIONAL,
}

PowerSource ::=INTEGER {
    mainBattery   (0),
    backupBattery (1)
}

TEMPowerMode ::= ENUMERATED {
   normal        (0),
   standby       (1),
   sleep_poll    (2),
   off           (3)
}

NetworkAccessStatus ::= SEQUENCE {
  simInfo                SIMInfo OPTIONAL,
  mobileNetwork          PrintableString(SIZE(0..127)) OPTIONAL -- 2G/3G/4G/wifi
}

Position ::= SEQUENCE {        
  -- format: milliarcsecond <=> degree * 3600000
  latitude                INTEGER(-2147483648..2147483647) OPTIONAL, -- 32 bits
  longitude               INTEGER(-2147483648..2147483647) OPTIONAL,  -- 32 bits
  altitude                INTEGER(-100..8091) OPTIONAL, -- the altitude in meter
  posCanBeTrusted         BOOLEAN OPTIONAL, -- false means TEM use last position instead of GPS, default is true
  carLocatorStatUploadEn  BOOLEAN OPTIONAL, -- can TEM upload position, user can enable/disable through IHU, default is true
  marsCoordinates		  BOOLEAN OPTIONAL  -- true means GCJ-02 coordinaes, false means WGS-84, defult is false
}
	
SIMInfo ::= SEQUENCE {
  msisdn       PrintableString(SIZE(1..32)) OPTIONAL,
  imsi         PrintableString(SIZE(1..32)) OPTIONAL,
  iccId        PrintableString(SIZE(1..32)) OPTIONAL
}


END

**Comment by eerimoq** [comment]
The ASN.1 schema has errors and cannot be compiled. There are trailing commas in a few places, for example `rvs (51),` and `vehicleStatus VehicleStatus OPTIONAL,`. Please fix all errors and I can have a look at it.

**Comment by xusunny** [comment]
Hello Erik,

Thanks for your kindness.
I have fixed all errors and The ASN.1 schema below can be compiled correctly.


VDS-CORE DEFINITIONS AUTOMATIC TAGS ::=BEGIN

VDServiceRequest ::= SEQUENCE {
	header 	RequestHeader, -- A request header, common for all requests
	body 	RequestBody OPTIONAL -- A request body specific for the type of service being executed
}

RequestHeader ::= SEQUENCE {
	requestid 			RequestId, -- An identifier of this request, must be unique to the sending party. If this request is an ACK, this is the identifier of the request being acknowledged
	timeStamp			TimeStamp, -- The time when this message was created
	eventId 			TimeStamp OPTIONAL, -- Identifier of the service event that is being executed, the value is the time when the event is created
	creatorId			CreatorId OPTIONAL, -- Identifies if this event was created by a TEM unit or CVC back-end
	messageTTL			MessageTTL OPTIONAL, -- Message time-to-live after which this request message should be discarded, no present means no limit
	requestType			RequestType OPTIONAL,-- Identifies the type of message, no presents means serviceRequest
	ackRequired			ACKRequired OPTIONAL-- If this request needs to be acknowledged, no present means false
}

RequestId ::= INTEGER (0..255)

TimeStamp ::= SEQUENCE {
  seconds INTEGER(0..2147483647),  -- UTC Timestamp
  milliseconds  INTEGER(0..999) OPTIONAL -- Millisecond within the second
}


CreatorId ::= ENUMERATED {
	ecu		(0),
	cvc		(1)
}

MessageTTL ::= INTEGER(0..86400)  -- Time in 10s increment (240 hours). 0=Unlimited TTL

RequestType ::= ENUMERATED{
	serviceRequest		(0),
	ack     			(1)
}

ACKRequired ::= BOOLEAN

RequestBody ::= SEQUENCE {
  serviceId 			ServiceId OPTIONAL, -- Determines the service that is being executed (defined in service specific ASN.1 file)
  serviceData 			ServiceData OPTIONAL, -- Service specific data (defined in service specific ASN.1 file)
  seq                   MessageSequence OPTIONAL -- Message sequence to prevent the replay attack
}

MessageSequence ::= INTEGER (0..255)

ServiceId ::= INTEGER{
	svt (41), -- SVT
	stn (44), -- Theft Notification
	rvs (51)  -- Remote status & dashboard
}(0..17575)

ServiceData ::= SEQUENCE {
	vehicleStatus           VehicleStatus  OPTIONAL	-- defined in specific device status ASN.1 file)
}

VehicleStatus ::= SEQUENCE {
 	basicVehicleStatus		   BasicVehicleStatus OPTIONAL,        -- the basic vehicle status
  	additionalVehicleStatus    AdditionalVehicleStatus OPTIONAL,   -- the additional vehicle status
  	temStatus                  TEMStatus OPTIONAL                 -- the TEM status
}

BasicVehicleStatus ::= SEQUENCE {
    position            Position ,
    speed               INTEGER , -- km/h   
	speedValidity		INTEGER (0..1) OPTIONAL, -- 0x0: valid, 0x1: Invalid
	direction           INTEGER (0..360) OPTIONAL
}

MaintenanceStatus ::=SEQUENCE {
  -- days to next service
  daysToService                INTEGER(-150..1890) OPTIONAL
}

AdditionalVehicleStatus ::= SEQUENCE {
  maintenanceStatus           MaintenanceStatus   OPTIONAL
}

TEMStatus ::= SEQUENCE {
	powerSource               PowerSource,
	powerMode                 TEMPowerMode,  
	networkAccessStatus       NetworkAccessStatus OPTIONAL, -- the network access information
	serialNumber              PrintableString OPTIONAL,
	imei                      PrintableString OPTIONAL,
	mpuVersion                PrintableString  OPTIONAL
}

PowerSource ::=INTEGER {
    mainBattery   (0),
    backupBattery (1)
}

TEMPowerMode ::= ENUMERATED {
   normal        (0),
   standby       (1),
   sleep-poll    (2),
   off           (3)
}

NetworkAccessStatus ::= SEQUENCE {
  simInfo                SIMInfo OPTIONAL,
  mobileNetwork          PrintableString(SIZE(0..127)) OPTIONAL -- 2G/3G/4G/wifi
}

Position ::= SEQUENCE {        
  -- format: milliarcsecond <=> degree * 3600000
  latitude                INTEGER(-2147483648..2147483647) OPTIONAL, -- 32 bits
  longitude               INTEGER(-2147483648..2147483647) OPTIONAL,  -- 32 bits
  altitude                INTEGER(-100..8091) OPTIONAL, -- the altitude in meter
  posCanBeTrusted         BOOLEAN OPTIONAL, -- false means TEM use last position instead of GPS, default is true
  carLocatorStatUploadEn  BOOLEAN OPTIONAL, -- can TEM upload position, user can enable/disable through IHU, default is true
  marsCoordinates		  BOOLEAN OPTIONAL  -- true means GCJ-02 coordinaes, false means WGS-84, defult is false
}
	
SIMInfo ::= SEQUENCE {
  msisdn       PrintableString(SIZE(1..32)) OPTIONAL,
  imsi         PrintableString(SIZE(1..32)) OPTIONAL,
  iccId        PrintableString(SIZE(1..32)) OPTIONAL
}

END

**Comment by xusunny** [comment]
the asn1 schema can be used to encode payload , but still have difference in encoded result compared to Objective Systems.INC tool.

**Comment by eerimoq** [comment]
I found the bug. It's fixed in 0.124.1. Install it with `pip install -U asn1tools`.

**Comment by xusunny** [comment]
but it doesn't support _

**Comment by eerimoq** [comment]
What do you mean?

**Comment by xusunny** [comment]
I know how to make compatible with _ , and thank you at last.
