### ISSUE TITLE
Compiling latest ieee1609_2.asn - handling ALL EXCEPT

### ISSUE THREAD

**Issue by DmitriKh** [eerimoq/asn1tools#33]
I tested the latest ieee1609_2.asn obtained from repository github.com/wwhyte-si/1609dot2-asn (all asn files combined into one Dot2all.asn)

[Dot2all.asn.txt](https://github.com/eerimoq/asn1tools/files/2447921/Dot2all.asn.txt)

**Error**: asn1tools.parser.ParseError: Invalid ASN.1 syntax at line 625, column 68: 'EndEntityType ::= BIT STRING {app (0), enrol (1) } (SIZE (8)) (ALL >!<EXCEPT {})': Expected ")".

Problematic line in ASN file is <pre>EndEntityType ::= BIT STRING {app (0), enrol (1) } (SIZE (8)) (ALL EXCEPT {})</pre>, specifically (ALL EXCEPT {}). 

<pre>
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import asn1tools
>>> oer = asn1tools.compile_files('Dot2all.asn', 'oer')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\asn1tools\compiler.py", line 329, in compile_files
    return compile_dict(parse_files(filenames, encoding),
  File "C:\Python27\lib\site-packages\asn1tools\parser.py", line 1761, in parse_files
    return parse_string(string)
  File "C:\Python27\lib\site-packages\asn1tools\parser.py", line 1727, in parse_string
    e.msg))
asn1tools.parser.ParseError: Invalid ASN.1 syntax at line 625, column 68: 'EndEntityType ::= BIT STRING {app (0), enrol (1) } (SIZE (8)) (ALL >!<EXCEPT {})': Expected ")".
</pre>

**Comment by eerimoq** [comment]
Hi,

I'm amazed by the complexity of ASN.1. When I started this library I knew that ASN.1 is used to serialize data, often for communication in heterogeneous systems. Simple types, such as SEQUENCE, INTEGER, BOOLEAN, could be packed very efficiently which is very useful where the bandwidth is limited. Now, this basic aspect of ASN.1 can be achieved writing a simple ASN.1 schema/specification that pretty much anyone can read and understand. Unfortunately, ASN.1 supports a lot of more or less useless constructs just making the whole thing hard to understand, read, maintain and implement.

As a quick fix I suggest that you modify the ASN.1 file to be accepted by asn1tools. As I don't know "ALL EXCEPT" very well I wont promise it wont affect the encoding.

I might try to implement support for this eventually, but I wont promise anything. Feel free to help out if this is important to you.

**Comment by DmitriKh** [comment]
Sure, I'll modify ASN file. Thank you. Dmitri
