### ISSUE TITLE
CompileError for 3GPP TS 38.473

### ISSUE THREAD

**Issue by tomaszwlf** [eerimoq/asn1tools#36]
Hi,
I'm trying to compile asn file define in 3gpp spec TS 38.473. Result of this is such error:

`  File "C:\Python27\lib\site-packages\asn1tools\codecs\compiler.py", line 628, in lookup_type_descriptor
    return self.lookup_in_modules('types', 'type', type_name, module_name)
  File "C:\Python27\lib\site-packages\asn1tools\codecs\compiler.py", line 623, in lookup_in_modules
    module_name))
asn1tools.errors.CompileError: Type 'OpenType' not found in module 'F1AP-Containers'.`

Is this error releated with one of limitations mentioned in README? or i'm doing something wrong
[F1AP.zip](https://github.com/eerimoq/asn1tools/files/2474294/F1AP.zip)

**Comment by eerimoq** [comment]
Yes, the `CLASS` keyword is not yet supported.

**Comment by tugstugi** [comment]
I am also interested for the CLASS support for ISO TS19091. If I want to add myself the CLASS keyword support, where should I start to look?

**Comment by eerimoq** [comment]
I started the class implementation on this branch: https://github.com/eerimoq/asn1tools/tree/class

It's far from complete and any help is appreciated.

**Comment by psonis** [comment]
I think I opened a similar issue (https://github.com/eerimoq/asn1tools/issues/59). Any progress with the Class implementation? Thanks.

**Comment by eerimoq** [comment]
Hi, no, and there will not be no progress unless someone other than me starts working on it. Sorry.
