### ISSUE TITLE
Comment markers not supported

### ISSUE THREAD

**Issue by lochotzke** [eerimoq/asn1tools#39]
Compiling [comment.asn](https://github.com/eerimoq/asn1tools/files/2487690/comment.asn.txt)
```ASN.1
/*
  This is a multi-line comment.
*/
```
gives me `asn1tools.parser.ParseError: Invalid ASN.1 syntax at line 1, column 1: '>!</*': Expected modulereference.`

**Comment by eerimoq** [comment]
Comments are removed here today: https://github.com/eerimoq/asn1tools/blob/master/asn1tools/parser.py#L1695-L1732

Removing comments using pyparsing was increadibly slow. Removing them before the parser cuts the parse time if half or so.

**Comment by eerimoq** [comment]
Version 0.130.0 supports both single line, "-- This is a comment.", and multiple line "/* This is a comment. */" comments.
