### ISSUE TITLE
hello, I have a few questions to ask

### ISSUE THREAD

**Issue by liweishi** [eerimoq/asn1tools#4]
test_per.py:
test_s1ap_14_4_0(self) is not success.
does  this tool not support all of the asn1 rule?

test_rrc_8_6_0 decode is not success.
some of type's encode/decode is not supported?

**Comment by eerimoq** [comment]
No, they are not fully supported as of today.

Feel free to implement the features you need and submit a PR. =)

**Comment by liweishi** [comment]
thanks for your answer
Now i know asn1tools does only support a subset of the ASN.1 specification syntax.
Would you like to tell me what ASN.1 specification syntax can asn1tools support ，or what cannot be supported? can you list for me?
are there any relevant documents for reference?
Besides，
As for the encoding and decoding part of the data types,  whether or not only the following data types in the link below are supported?
http://asn1tools.readthedocs.io/en/latest/#types

in order to meet the needs of current project, i intend to improve this tool to support all the ASN.1 specification syntax in 3GPP(X2AP/F1AP/RRC), 
and also to support all the relevant encode/decode of all types in 3GPP(X2AP/F1AP/RRC).
i really hope i can get you support and assistance, hope to cooperate with you. thank you very much.

**Comment by eerimoq** [comment]
I know that the CLASS keyword does only work in very specific cases. Also, extensions ("..." in the ASN.1 specification) and constraints are not fully supported, and I'm sure extensions will be required in later versions of 3GPP specifications. The UPER codec should work for most types, but PER is less mature. It's rather easy to add support for additional types in the codecs, so it should not be a big issue. It's more work to make CLASS, OpenType and extensions work properly.

The best reference/documentation is the source code itself. It should be fairly straight forward and easy enough to understand.

I'll gladly answer questions and review PR:s as we go along! =)

**Comment by liweishi** [comment]
Thanks for your reply. recently i am learning the source code, but i think the algorithm of codecs of different types by myself is difficult. Can you give me some suggestions for doing this algorithm? (In former cases, I used the codecs library provided by a third party. )By the way, what does OpenType mean? What type of syntax does OpenType belong to? Thanks!

**Comment by eerimoq** [comment]
It's easy to find the ASN.1 specifications on the internet, and they are well written and fairly easy to understand. They are called X.680, X.681, etc.

Use Google to find the definition of the OpenType. It can be any type I think. =)
