### ISSUE TITLE
Named constants not supported

### ISSUE THREAD

**Issue by lochotzke** [eerimoq/asn1tools#40]
Compiling [constant.asn](https://github.com/eerimoq/asn1tools/files/2487700/constant.asn.txt)
```ASN.1
Foo DEFINITIONS ::= BEGIN

    Constants ::= INTEGER  {
        min     (-1),
        max     (1),
        unknown (2)
    } (-1..2)

    A ::= Constants (min..max)
    B ::= Constants (unknown)

END
```
gives me `asn1tools.errors.CompileError: Value 'min' not found in module 'Foo'.`

**Comment by eerimoq** [comment]
Probably [this function](https://github.com/eerimoq/asn1tools/blob/master/asn1tools/codecs/compiler.py#L759) has to look into named constants as well.

**Comment by eerimoq** [comment]
Added in version 0.137.0.
