### ISSUE TITLE
Import of import not supported

### ISSUE THREAD

**Issue by lochotzke** [eerimoq/asn1tools#41]
Compiling [import.asn](https://github.com/eerimoq/asn1tools/files/2487723/import.asn.txt)
```ASN.1
A
DEFINITIONS AUTOMATIC TAGS ::= BEGIN

    EXPORTS ALL;

    Type ::= INTEGER

END

B
DEFINITIONS AUTOMATIC TAGS ::= BEGIN 

    IMPORTS 

        Type FROM A

    ;

    AnotherType ::= Type

END

C
DEFINITIONS AUTOMATIC TAGS ::= BEGIN 

    IMPORTS 

        Type FROM B

    ;

    AndAnotherType ::= Type

END
```
gives me `asn1tools.errors.CompileError: Type 'Type' imported by module 'C' not found in module 'B'.`

**Comment by eerimoq** [comment]
This is the method that is used to find a type (or so called type descriptor): https://github.com/eerimoq/asn1tools/blob/master/asn1tools/codecs/compiler.py#L756

It looks for types in current module and its imports, but it does not follow imports in the exporting module.

**Comment by eerimoq** [comment]
Fixed on master.
