### ISSUE TITLE
Invalid ASN.1 syntax parsing SEQUENCE

### ISSUE THREAD

**Issue by Nofre** [eerimoq/asn1tools#43]
I am trying to compile a file with some sentences like  ```SEQUENCE (SIZE (1..4),...)```, but these lines raise a ParseError.

Example:
```
GicPart::= SEQUENCE {
	detectionZoneIds			SEQUENCE (SIZE (1..8,...)) OF Zid OPTIONAL,
	its-Rrid				VarLengthNumber OPTIONAL,
	relevanceZoneIds		SEQUENCE (SIZE (1..8,...)) OF Zid OPTIONAL,
	direction				Direction OPTIONAL,
	driverAwarenessZoneIds	SEQUENCE (SIZE (1..8,...)) OF Zid OPTIONAL,
	minimumAwarenessTime	INTEGER (0..255) OPTIONAL,
	applicableLanes			SEQUENCE (SIZE (1..8,...)) OF LanePosition OPTIONAL,
	iviType					IviType,
	iviPurpose				IviPurpose OPTIONAL,
	laneStatus				LaneStatus OPTIONAL,
	vehicleCharacteristics	SEQUENCE (SIZE (1..8, ...)) OF CompleteVehicleCharacteristics OPTIONAL,
	driverCharacteristics	DriverCharacteristics OPTIONAL,
	layoutId				INTEGER(1..4,...) OPTIONAL,
	preStoredlayoutId		INTEGER(1..64,...) OPTIONAL,
	roadSignCodes			SEQUENCE (SIZE (1..4),...) OF RSCode,
	extraText				SEQUENCE (SIZE (1..4),...) OF Text (WITH COMPONENTS {layoutComponentId, language, textContent (SIZE(1..32))}) OPTIONAL,
	...
	}
```

```
asn1tools.parser.ParseError: Invalid ASN.1 syntax at line 91, column 50: 'roadSignCodes                   SEQUENCE >!<(SIZE (1..4),...) OF RSCode,': Expected "{".
```

There is the file that I want to compile, ISO19321(2015)IVIv1.asn, and his dependencies
[standards.tar.gz](https://github.com/eerimoq/asn1tools/files/2533945/standards.tar.gz)

**Comment by eerimoq** [comment]
If I'm not mistaken you an change `(SIZE (1..4), ...)` to `(SIZE (1..4, ...))` without affecting the encoding.

**Comment by eerimoq** [comment]
I added support for `(SIZE (1..4), ...)` on master. There are other constructs in your files that are not supported, so this fix will not help you much. For example the `DATE` type is not yet supported. Also `_` in type names are not supported. Neither is the `CLASS` keyword.

**Comment by Nofre** [comment]
Thanks! I don't need to compile this file yet, I was testing all files that I will need in a future for a project. Maybe in a few months I will have to do it because this file will be mandatory.
