### ISSUE TITLE
Are there plans to support parameterization?

### ISSUE THREAD

**Issue by jingevent** [eerimoq/asn1tools#47]
The following is in my ASN file：
```
SetupRelease { ElementTypeParam } ::= CHOICE {
    release         NULL,
    setup           ElementTypeParam
}
LocationMeasurementIndication-IEs ::=       SEQUENCE {
    measurementIndication       SetupRelease { LocationMeasurementInfo},
    nonCriticalExtension        SEQUENCE{}                               OPTIONAL
}
```

$ compile -i per 331.asn                                                                                                                
error: Type 'ElementTypeParam' not found in module 'NR-RRC-Definitions'.

**Comment by eerimoq** [comment]
I've considered implementing it, but after the `CLASS` keyword with friends. I've absolutely no idea on when this will be completed. If parameterization is important to you you probably have to use another library, or implement it yourself, sorry.

**Comment by studentbrad** [comment]
There is a simple solution to avoid using another library, or implementing the feature yourself: hack the dictionary.
Here is an example using SetupRelease: https://gist.github.com/studentbrad/3357811bf5b48ffeddda54255de7775b
Here, my function compileFiles() is equivalent to asn1tools.compile_files(), but it supports parameterized SetupRelease.
