### ISSUE TITLE
UTF8String with uper

### ISSUE THREAD

**Issue by xusunny** [eerimoq/asn1tools#48]
hello Eric,I encounter an issue when encoding UTF8String  with uper and checkConstaints=True, it throws error
"Encode Error installationorder:uuid:Expected a Character in ' ',but got 'v'(0x76)."
I debugged and find "permitted_alphabet" in  constaints_checker.py is ' ', can you help me with the issue? lots of thanks.

**Comment by eerimoq** [comment]
This might be fixed on the master branch. Give it a try and I can create a new release if it works.

**Comment by xusunny** [comment]
hello Eric, I just tested on master branch,and no error when check_constraints=True,but asn1tools seem like using per style to encode length.e.g.
uuid::=UTF8String(Size(1..36)), asn1tools don't minus 1 when encoding length, and the encoded result can't be decoded by marben.
Do I think right?

**Comment by eerimoq** [comment]
I think Marben is wrong. Size constraints are ignored by PER and UPER for UTF8String as its not a known-multiplier character string type.

See 27.6 in https://www.itu.int/ITU-T/studygroups/com17/languages/X.691-0207.pdf.

**Comment by eerimoq** [comment]
The new release is called 0.138.0, available on PyPI.

**Comment by xusunny** [comment]
ok, thank you for new release, about UTF8String,I should check again.

**Comment by eerimoq** [comment]
Any news?

**Comment by xusunny** [comment]
I think you are right about length encoding with uper, but there's exactly difference when encoding UTF8String compared to marben,  I paste here wish you can help me find out why, the bold is difference.

from marben:
d6 93 39 8b 26 6d 1a b6 6e e1 
cb 0a d2 67 31 64 cd a3 56 cd 
dc 39 60 c5 93 36 8d 5b 37 70 
e5 81 93 06 2e 16 b1 64 b5 8b 
04 0c 5a ba 62 cd d3 06 08 22 
d3 a8 38 62 64 66 68 6a 6c 6e 
70 72 60 62 64 66 68 6a 6c 6e 
70 72 60 62 64 66 68 6a 6c 6e 
71 4c bd b2 f2 f3 d3 46 9d d9 
d0 69 e6 83 76 fe 88 37 eb 

from asn1tools:
d6 93 39 8b 26 6d 1a b6 6e e1
cb 0a d2 67 31 64 cd a3 56 cd
dc 39 60 c5 93 36 8d 5b 37 70 
e5 **85d**93 06 2e 16 b1 64 b5 8b 
04 0c 5a ba 62 cd d3 06 08 22 
d3 a8 38 62 64 66 68 6a 6c 6e 
70 72 60 62 64 66 68 6a 6c 6e
70 72 60 62 64 66 68 6a 6c 6e 
71 4c bd b2 f2 f3 d3 46 9d d9 
d0 69 e6 83 76 fe 88 37 eb **0**

and .asn specification is 
UUID ::= SEQUENCE {
   uuid   PrintableString(SIZE(36)) -- Constrained to an UUID
}
OpOTAAssignmentNotification-Notification ::= SEQUENCE {
	installationorder UUID,
	timestamp ISOTimeStamp,
	newstatus UTF8String(SIZE(2..28)),
	reason PrintableString(SIZE(0..22)) OPTIONAL
}
ISOTimeStamp ::= SEQUENCE {
	timestamp PrintableString(SIZE(0..24))
}

input data is
UUID = {'uuid': 'VIN1234567890VIN12345678901234567890'}
ISOTimeStamp = {'timestamp': '2018-12-10 15:13:00 EST'}
OpOTAAssignmentNotification_Notification = {'installationorder': UUID,
                                                'timestamp': ISOTimeStamp,
                                                'newstatus': u'1234567890123456789012345678',
                                                'reason': 'everything is not ok'}

Finally, happy Christmas Day!

**Comment by eerimoq** [comment]
I don't have time to troubleshoot this in detail, but I think asn1tools is correct, and Marben wrong.

**Comment by xusunny** [comment]
sorry for interrupting you,but it's because asn specification inconsistent which leads to different encode result.
