### ISSUE TITLE
DER: error while encoding OCTET STRING more than 255 bytes long 

### ISSUE THREAD

**Issue by olegst90** [eerimoq/asn1tools#5]
When I try to encode an OCTET STRING more than 255 bytes long, I get an exception in _codecs/der.py_:
`490:        encoded.append(len(data))`
because the implementation seems not to support multibyte length fields. The same must happen with other array types.

Please, mention this limitation in the lib description.

**Comment by eerimoq** [comment]
It clearly states that all codecs are under development. I'll implement this tonight if it's easy, which it likely is.

**Comment by olegst90** [comment]
Thank you in advance.

**Comment by eerimoq** [comment]
There is a fix in commit 535f0f0473b57a3b7ec551546af4058215d8cf8e, which is released to PyPI in version 0.23.0.

I'm sure you will find other missing features, and likely a bug or two. Just post any issues here and I'll fix them.

**Comment by olegst90** [comment]
Thank you so much, I've already tried and it worked.
