### ISSUE TITLE
When decoding also return the number of bytes consumed

### ISSUE THREAD

**Issue by MBradbury** [eerimoq/asn1tools#52]
When decoding it would be useful if the number of bytes from the buffer that has been consumed is returned along with the decoded object. [decode_length](https://asn1tools.readthedocs.io/en/latest/#asn1tools.compiler.Specification.decode_length) is not useful to me as my objects are uper encoded.

For example, asn1c has a function [uper_decode_complete](https://github.com/vlm/asn1c/blob/master/skeletons/per_decoder.c#L11) that returns the number of bytes consumed.

This is useful when there is other data located after the ASN.1 encoded object and the length of the ASN.1 encoded object has not been previously specified.

**Comment by eerimoq** [comment]
Feel free to implement it. Sounds useful.

**Comment by MBradbury** [comment]
Do you have any suggestions where I might start? I had a look through the code, but it wasn't clear to me where I should look to modify the code,
For now I have solved this by re-encoding the decoded contents to get the length.

**Comment by eerimoq** [comment]
Start by designing the new decode method, and then make required changes throughout the package.

However, I would recommend framing the encoded UPER data by introducing a length field in the stream of data. It's obviously not required, but more robust in case of bugs in the encoder or decoder.

**Comment by eerimoq** [comment]
Closing in lack of response.

**Comment by MBradbury** [comment]
Initial progress was made at https://github.com/MBradbury/asn1tools but I ran into test errors such as:

$ python3 -m unittest tests.test_uper
..........................Failed to decode type with name B.
E...............
======================================================================
ERROR: test_real (tests.test_uper.Asn1ToolsUPerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/duser/asn1tools/asn1tools/codecs/per.py", line 446, in read_length_determinant
    }[value]
KeyError: 192

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/duser/asn1tools/tests/test_uper.py", line 147, in test_real
    self.assert_encode_decode2(foo, type_name, decoded, encoded)
  File "/home/duser/asn1tools/tests/utils.py", line 69, in assert_encode_decode2
    decoded, decoded_bits = specification.decode2(type_name, encoded_message)
  File "/home/duser/asn1tools/asn1tools/compiler.py", line 193, in decode2
    decoded, decoded_bits = type_.decode2(data)
  File "/home/duser/asn1tools/asn1tools/codecs/per.py", line 1991, in decode2
    decoded = self._type.decode(decoder)
  File "/home/duser/asn1tools/asn1tools/codecs/per.py", line 815, in decode
    decoded = self.decode_root(decoder)
  File "/home/duser/asn1tools/asn1tools/codecs/per.py", line 831, in decode_root
    value = member.decode(decoder)
  File "/home/duser/asn1tools/asn1tools/codecs/per.py", line 1098, in decode
    length = decoder.read_length_determinant()
  File "/home/duser/asn1tools/asn1tools/codecs/per.py", line 450, in read_length_determinant
    value))
asn1tools.codecs.DecodeError: a: Bad length determinant fragmentation value 0xc0.

----------------------------------------------------------------------
Ran 42 tests in 4.767s

FAILED (errors=1)

**Comment by eerimoq** [comment]
Do you intend to continue the implementation? In that case we can reopen the issue.
