### ISSUE TITLE
PER encoding of BMPString

### ISSUE THREAD

**Issue by xuhe5** [eerimoq/asn1tools#56]
Hello eerimoq,
Thank you for asn1tools. I am trying to use this library to parse H.225 messages, they are ASN.1 encoded via PER. I run into issues with BMPStrings - the length does not match the payload. I believe this is because asn1tools classifies BMPStrings as StringTypes rather than KnownMultiplierStrings, so the adaptive length computations are not applied as they are for, say, IA5Strings.
I have made a small patch that changes the classification of BMPStrings, and also handles multi-byte encodings in the main KnownMultiplierStrings decoding routines (I use wireshark decoder as a guide for this). For me this resolves the problem. However, I believe this patch is incomplete (e.g. I do not handle encoding).
Questions:
1. Is changing of BMPStrings correct?
2. If so, will fix for this be possible?
3. If so, would you like me to submit a PR as basis for this fix?
Thank you.

**Comment by eerimoq** [comment]
I don't know the details about BMPString.

Improvements and new features are always welcome. Feel free to submit a PR and I'll have a look at it.

**Comment by xuhe5** [comment]
I have created a pull request [here](https://github.com/eerimoq/asn1tools/pull/57).
The tests all pass except some minor codespell errors that were already present.
Please review it when you have time and modify it as you like.
Thank you.

**Comment by eerimoq** [comment]
Part of 0.146.3.
