### ISSUE TITLE
Records spaced out by "xFF" fillers cannot be read by BER.decode

### ISSUE THREAD

**Issue by edsase** [eerimoq/asn1tools#58]
Thanks for your wonderful library which I have been using to successfully decode Hauwei CDR files. Today, I started a project involving ZTE CDR files with records separated by "\xFF". The BER.decode only decodes the first record but cannot decode the rest of the CDR once it hits the  "\xFF". It fails silently and only returns the first record.

Is there a way for the BER.decode() function to skip over this gap fillers and move the next start of record ?
[Here](https://drive.google.com/open?id=1f5xAFnBmCj3poC9ogoN2Og9UWljPSGgA) is the cdr asn1 specification and [here ](https://drive.google.com/open?id=1a2Su6072_6fK6lOctW67QDqyu1fIiVRV)is an example ZTE CDR file.
Thanks for your help!

**Comment by eerimoq** [comment]
It's not pretty, but seems to do the job:

``` python
import asn1tools

ber = asn1tools.compile_files('zte_cdr.asn', 'ber')
xer = asn1tools.compile_files('zte_cdr.asn', 'xer')

offset = 0

with open('B2019040114019.dat', 'rb') as fin:
    data = fin.read()

while offset < len(data):
    offset += ber.decode_length(data[offset:])

    while offset < len(data) and data[offset] == 0xff:
        offset += 1

    if offset < len(data):
        decoded = ber.decode('CallEventRecord', data[offset:])
        encoded = ber.encode('CallEventRecord', decoded)
        print(xer.encode('CallEventRecord', decoded, indent=4).decode('ascii'))
```

**Comment by edsase** [comment]
It worked like a charm! Thank you @eerimoq !
