### ISSUE TITLE
OER decoding error

### ISSUE THREAD

**Issue by ttt710516** [eerimoq/asn1tools#60]
I have a simple ASN files as the follows
***********
Test DEFINITIONS AUTOMATIC TAGS ::= BEGIN 
Abc ::= INTEGER (1..MAX)
END
***********

And I write the following code
***********
coer = asn1tools.compile_files('asn1\\test.asn', codec='oer')
byte_str = bytes.fromhex('0180')
print(coer.decode('Abc', byte_str))
***********

I think the result should be 128. However, I got -128.
I think it is an incorrect result

**Comment by eerimoq** [comment]
Thanks for the bug report.

Fixed in version 0.146.4, available on PyPI.

**Comment by ttt710516** [comment]
I have tried it. It's nice now.
Thanks
