### ISSUE TITLE
Decoding inner encoded data

### ISSUE THREAD

**Issue by spenat** [eerimoq/asn1tools#67]
In this example there is a inner encoded sequence of octet strings that triggers a OutOfDataError
Here is the asn-file: 

[test.asn.txt](https://github.com/eerimoq/asn1tools/files/3949550/test.asn.txt)

Here is the python-code producing the error:

[asn1tools_testcase.py.txt](https://github.com/eerimoq/asn1tools/files/3949573/asn1tools_testcase.py.txt)

**Comment by eerimoq** [comment]
The example is complex and it's hard to understand what you are trying to do, but it looks like you encode as SPP and decode as EHPD. The encode and decode types must match.

**Comment by spenat** [comment]
I simplified the testcase a bit to make it clearer.
I am trying to encode SPP and put it into MDM as data. Encode the whole MDM structure and then decode the whole thing. 

I renamed test.asn to test.asn.txt and asn1tools_testcase.py to asn1tools_testcase.py.txt to upload them. To run the testcase and get the error you need to rename them back.

heres the traceback: 

Traceback (most recent call last):
  File "asn1tools_testcase.py", line 70, in <module>
    main()
  File "asn1tools_testcase.py", line 66, in main
    result = decode_asn1uper_to_json(UPER_DATA)
  File "asn1tools_testcase.py", line 21, in decode_asn1uper_to_json
    json_list = decode_uper_to_json(asn_type, asn_info_content, base64_data)
  File "asn1tools_testcase.py", line 29, in decode_uper_to_json
    check_constraints=True)
  File "site-packages\asn1tools\compiler.py", line 163, in decode
    decoded = type_.decode(data)
  File "site-packages\asn1tools\codecs\uper.py", line 475, in decode
    return self._type.decode(decoder)
  File "site-packages\asn1tools\codecs\per.py", line 851, in decode
    decoded = self.decode_root(decoder)
  File "site-packages\asn1tools\codecs\per.py", line 865, in decode_root
    value = member.decode(decoder)
  File "site-packages\asn1tools\codecs\uper.py", line 162, in decode
    decoded_element = self.element_type.decode(decoder)
  File "site-packages\asn1tools\codecs\uper.py", line 303, in decode
    return decoder.read_bytes(length)
  File "site-packages\asn1tools\codecs\per.py", line 440, in read_bytes
    return self.read_bits(8 * number_of_bytes)
  File "site-packages\asn1tools\codecs\per.py", line 426, in read_bits
    raise OutOfDataError(self.number_of_read_bits())
asn1tools.codecs.OutOfDataError: ch: out of data at bit offset 112 (14.0 bytes)



[asn1tools_testcase.py.txt](https://github.com/eerimoq/asn1tools/files/3951179/asn1tools_testcase.py.txt)

[test.asn.txt](https://github.com/eerimoq/asn1tools/files/3951182/test.asn.txt)

**Comment by eerimoq** [comment]
Try using ASN.1 Playground to encode and decode as in the example. If it works there, please let me know. If it fails there as well, your use case is not supported by ASN.1.

https://asn1.io/asn1playground/

**Comment by spenat** [comment]
It works.
Encoding  {"ch": ["31","32","33","34"]} into "0004000131000132000133000134" works
Encoding {"mD": {"data": "0004000131000132000133000134"}} just gives a black screen for some reason, but i can encode it with the library and i get "001a0008000262000264000266000268" which can be decoded by asn1.io playground

**Comment by eerimoq** [comment]
See inline comments.

``` python
def main():
    jsondatainner = {"ch": ["31","32","33","34"]}
    uper_inner  = encode_json_to_uper(get_asn_content("test.asn"), json.dumps(jsondatainner), 'SPP')
    print(f'uper_inner: {uper_inner}')
    JSON_DATA = {'mD': {"data": base64_to_hex(uper_inner) }}
    JSON_STR = json.dumps(JSON_DATA)
    print(f"JSON_STR: {JSON_STR}")
    # UPER_DATA is MDM encoded.
    UPER_DATA = make_data_from_json(JSON_STR, "MDM")
    print(f'UPER_DATA: {UPER_DATA}')
    HEX_DATA = base64_to_hex(UPER_DATA)
    print(f'HEX_DATA : {HEX_DATA}')
    # Decoding UPER_DATA as SPP, which will fail becasuse it was encoded as MDM.
    result = decode_asn1uper_to_json(UPER_DATA)
```

with this code it works:

``` python
def main():
    jsondatainner = {"ch": ["31","32","33","34"]}
    uper_inner  = encode_json_to_uper(get_asn_content("test.asn"), json.dumps(jsondatainner), 'SPP')
    print(f'uper_inner: {uper_inner}')
    JSON_DATA = {'mD': {"data": base64_to_hex(uper_inner) }}
    JSON_STR = json.dumps(JSON_DATA)
    print(f"JSON_STR: {JSON_STR}")
    # UPER_DATA is MDM encoded.
    UPER_DATA = make_data_from_json(JSON_STR, "MDM")
    print(f'UPER_DATA: {UPER_DATA}')
    HEX_DATA = base64_to_hex(UPER_DATA)
    print(f'HEX_DATA : {HEX_DATA}')
    # Decoding UPER_DATA as SPP, which will fail becasuse it was encoded as MDM.
    result = decode_asn1uper_to_json(UPER_DATA, 'MDM')
```

**Comment by spenat** [comment]
Yes, you are right. This issue can be closed. Thank you for the help.
