### ISSUE TITLE
Issue in Encoding BIT STRING of variable size

### ISSUE THREAD

**Issue by 23Shubham** [eerimoq/asn1tools#69]
Providing a BIT STRING to asn1tools using PER codec.

**key :: BIT STRING SIZE((1..160, ...))**

key
value = (bytesarray,len(bytesarray))
asn1_obj = asn1tools.compile_files(asn1_file, 'per', numeric_enums=True)

encoded_data = asn_object.encode(key, value)

We get binary and a IP address of defined length as i have provided 32 length.
But the output i am getting is more than 32 bits.

**Comment by eerimoq** [comment]
Please provide a minimal working example to make debugging easier.

**Comment by 23Shubham** [comment]
I have my asn1_file:

TransportLayerAddress ::= BIT STRING (SIZE(1..160, ...))

**key -->** 'transportLayerAddress'
**value -->** (b'\x1f\xc0\xe9\x02\x1f', len(b'\x1f\xc0\xe9\x02\x1f'))

asn1_obj = asn1tools.compile_files(asn1_file, 'per', numeric_enums=True)
encoded_data = asn_object.encode(key, value)

but i am getting data of more than 32 bits

**Comment by eerimoq** [comment]
The second element in the value tuple should be the bumber of bits, not the number of bytes. However, I doubt that solves the issue, and I strongly suggest that you write a minimal working example. There will be misunderstandings if you don't, I'm sure.

**Comment by 23Shubham** [comment]
I have provided the element in tuple (data,number of bits)

using the 'per' codec 
under BIT STRING >> encode function:

I have aligned the encoder value before appending the constrained whole number as earlier encoded value should also be aligned.
This is giving me the desired output i need.

**I made this change**

    def encode(self, data, encoder):
        data, number_of_bits = data
        if self.has_named_bits:
            data, number_of_bits = self.rstrip_zeros(data, number_of_bits)
        print("this is data", data)
        print("this is number of bits", number_of_bits)

        if self.number_of_bits is None:
            return self.encode_unbound(data, number_of_bits, encoder)



        elif self.minimum != self.maximum:
           #This is my change aligning the values before appending the constrained whole number as 
             earlier encoded value should also be aligned.
            **encoder.align()**


            encoder.append_constrained_whole_number(number_of_bits,
                                                    self.minimum,
                                                    self.maximum,
                                                                self.number_of_bits)

            encoder.align()
            print("After encoder align",encoder.value)
        elif self.minimum > 16:
            encoder.align()
        encoder.append_bits(data, number_of_bits)

Please tell is it correct?

I am getting right value now.

**Comment by eerimoq** [comment]
I'm sorry, but the added align() makes tests fails, so it's not correct.

I tried to reproduce the issue both with asntools and https://asn1.io/asn1playground/, but I couldn't. 

Please provide a minimal example script I can use to reproduce the issue.

**Comment by 23Shubham** [comment]
This is my code

load the json message in encoder
and run encoder
encoder.py
asn1_spec.asn
initialcontextsetupresponse.json
[asn1_spec.txt](https://github.com/eerimoq/asn1tools/files/4234618/asn1_spec.txt)
[encoder.txt](https://github.com/eerimoq/asn1tools/files/4234619/encoder.txt)
[initialcontextsetup_response.txt](https://github.com/eerimoq/asn1tools/files/4234620/initialcontextsetup_response.txt)

**Comment by eerimoq** [comment]
I get this with asn1tools 0.146.6:

And by the way, I would be surprised if that ASN.1 spec works as it uses the CLASS keyword and parameterization. See limitations: https://github.com/eerimoq/asn1tools#known-limitations

```
python3 encoder.py
Traceback (most recent call last):
  File "encoder.py", line 172, in <module>
    asn1_obj_encoder = asn1tools.compile_files(asn1_file, 'per', numeric_enums=True)
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/compiler.py", line 354, in compile_files
    numeric_enums)
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/compiler.py", line 284, in compile_dict
    numeric_enums),
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/codecs/per.py", line 2286, in compile_dict
    return Compiler(specification, numeric_enums).process()
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/codecs/compiler.py", line 186, in process
    self.pre_process()
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/codecs/compiler.py", line 234, in pre_process
    module_name)
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/codecs/compiler.py", line 476, in pre_process_parameterization_step_1
    module_name)
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/codecs/compiler.py", line 495, in pre_process_parameterization_step_1_type
    module_name)
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/codecs/compiler.py", line 539, in pre_process_parameterization_step_1_type
    parameterized_module_name)
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/codecs/compiler.py", line 578, in pre_process_parameterization_step_1_dummy_to_actual_type
    module_name)
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/codecs/compiler.py", line 588, in pre_process_parameterization_step_1_dummy_to_actual_type
    if parameter['type'] == dummy_parameter:
TypeError: string indices must be integers
```

**Comment by 23Shubham** [comment]
I am using the same version 0.146.6, able to compile this asn file.

**Comment by 23Shubham** [comment]
We can use the asn found in your directory:
https://github.com/eerimoq/asn1tools/blob/master/tests/files/3gpp/s1ap_14_4_0.asn

and check the output

**Comment by 23Shubham** [comment]
Is it possible to compile above mentioned asn file and run our code to check for BIT STRING

**Comment by eerimoq** [comment]
Sorry, but I already tried to reproduce the error and failed. I'm waiting for you to show exactly what you do and what the problem is with asn1tools.

**Comment by 23Shubham** [comment]
Okay. So how can we do this? I'll show you what i am doing and where i am facing a issue

**Comment by 23Shubham** [comment]
Eerimoq we can use the asn file in your directory to check issue i am facing with asn1tools.

https://github.com/eerimoq/asn1tools/blob/master/tests/files/3gpp/s1ap_14_4_0.asn

**Comment by 23Shubham** [comment]
This is my IE of s1ap which needs to be encoded. Full json message is attached.

{
                              "id": 51,
                              "criticality": 1,
                              "value":
                                  {
                                  "E-RABSetupListCtxtSURes":
                                      [
                                          {
                                              "id" : 50,
                                              "criticality": 1,
                                              "value":
                                                  {
                                                  "E-RABSetupItemCtxtSURes":
                                                      {
                                                      "e-RAB-ID" : 5,
                                                      "transportLayerAddress" : "c0e9021f",
                                                      "gTP-TEID": "00000001"
                                                       }

*****************************************************************************************************

Attaching the logs of change in encoder value:
Under BIT STRING > encode

**Changed PER Codec**

        elif self.minimum != self.maximum:
            print("Inside encode Encoder value",encoder.value)
            encoder.align()
            print("Check encoder align above",encoder.value)
            encoder.append_constrained_whole_number(number_of_bits,
                                                    self.minimum,
                                                    self.maximum,
                                                                self.number_of_bits)
																
			print("added",encoder)
            encoder.align()
            print("After encoder align",encoder.value)
																
OUTPUT:
																

Inside encode Encoder value 5                  -- Getting this value in encoder when e-RAB-ID is encoded
Check encoder align above 10
added 0a1f									   -- Whole thing is first aligned then next value is appended
After encoder align 2591						    -- next IE that needs to be encoded is of type BIT STRING SIZE(1..160,...)
													
																
---------------------------------------------------------------------------------------------													
																
**Original PER Codec** 																
																
																
      elif self.minimum != self.maximum:
            print("Inside encode Encoder value",encoder.value)
            encoder.append_constrained_whole_number(number_of_bits,
                                                    self.minimum,
                                                    self.maximum,
                                                                self.number_of_bits)
            print("added",encoder)
            encoder.align()
            print("After encoder align",encoder.value)												
																
																
OUTPUT:

Inside encode Encoder value 5					-- Getting this value in encoder when e-RAB-ID is encoded
Check encoder align above 5
added 0a3e										-- before encoding next thing it is adding value to the encoder value. We are facing a issue here
After encoder align 2622						    --next IE that needs to be encoded is of type BIT STRING SIZE(1..160,...)

[initialcontextsetup_response.txt](https://github.com/eerimoq/asn1tools/files/4275454/initialcontextsetup_response.txt)

**Comment by eerimoq** [comment]
asn1tools does not support the S1AP spec.

**Comment by 23Shubham** [comment]
We are compiling the asn file defining s1ap IE

**Comment by eerimoq** [comment]
Maybe so, but encoding and decoding does not work as you have noticed. You're welcome to add support for S1AP.

**Comment by 23Shubham** [comment]
I am able to encode and decode the s1ap messages using asn1tools. Facing
issue for BIT STRING of variable size only rest everything is encoding and
decoding properly.
