### ISSUE TITLE
Decoding error

### ISSUE THREAD

**Issue by vitec6630** [eerimoq/asn1tools#7]
Hello!

I'm trying to use this decoder for ber decoding. Binary data in the file below. This file contents asn1 binary data which were encoded by asn1c library. It's decoded by https://lapo.it/asn1js/ perfectly. But when I tried use your library I get error "expected SEQUENCE with tag 0x30 but got 0x80"
[dump.txt](https://github.com/eerimoq/asn1tools/files/1687972/dump.txt)

Asn1 stucture file

[structure.txt](https://github.com/eerimoq/asn1tools/files/1687980/structure.txt)

**Comment by eerimoq** [comment]
Hi,

I found two bugs in the BER codec thanks to your report:

1. The SEQUENCE OF decoder ignores the tag, which it shouldn't. This is easy to fix, and I already fixed it locally.

2. AUTOMATIC, EXPLICIT and IMPLICIT tagging is not compliant to the ASN.1 specifications. Tagging of the CHOICE type is wrong for sure. I'll have to investigate this further.

**Comment by eerimoq** [comment]
I fixed 1. in b7b9e285dcba5d9e7381033fee72ddcc8902b048. 2. will take longer to fix. Unclear when it will be ready.

**Comment by eerimoq** [comment]
Version 0.25.0 can successfully decode dump.txt using your schema and type VoiceManagerMsg. It's uploaded to PyPI, install with `pip install -U asn1tools`.

``` python
>>> import asn1tools
>>> f = asn1tools.compile_files('structure.txt')
>>> f.decode('VoiceManagerMsg', open('dump.txt', 'rb').read())
{'phone': {'time-st': {'nsec': 353258578, 'sec': 1517541551}, 'call-id': 's8isiqqsqgroakkqsqgk3tnqgkdiasod@10.18.5.64', 'phone-msg': {'m-call': {'group-id': 'intouch', 'call
ed-pn': {'presentation': 0, 'nai': 4, 'number': '79958290016'}, 'calling-pn': {'presentation': 0, 'nai': 4, 'number': '79832650742'}, 'called-contact': {'uri': {'host': '11.
11.1.4', 'user': '+79958290016'}, 'nickname': '+79958290016'}, 'calling-contact': {'uri': {'host': '10.51.34.6', 'user': '+79832650742'}, 'nickname': '+79832650742', 'parame
ters': [{'value': '8a11i8td-CC-1003-OFC-14', 'key': 'tag'}]}, 'location-pn': {'presentation': 0, 'nai': 4, 'number': '79135999991'}}}}}
>>> 
```
