### ISSUE TITLE
ParseError: Invalid ASN.1 syntax at line 1817, column 112:

### ISSUE THREAD

**Issue by gas007wei** [eerimoq/asn1tools#70]
Hi,
I extracted the asn1 schema from 3gpp spec and tried to run 'asn1tools.compile_files('NGAP_IEs.asn')' and got an ParseError. Meanwhile I used asn1c to parsing the same 'NGAP_IEs.asn' file and passed.

[NGAP_IEs.zip](https://github.com/eerimoq/asn1tools/files/4398569/NGAP_IEs.zip)

**Comment by eerimoq** [comment]
The file is empty.

`IEs` hits that classes are used, which are not supported.

**Comment by gas007wei** [comment]
sorry for uploading the wrong file...
I upload the right asn1 file again.
[NGAP-IEs.zip](https://github.com/eerimoq/asn1tools/files/4398592/NGAP-IEs.zip)
