### ISSUE TITLE
Issue in running the libarary after installation

### ISSUE THREAD

**Issue by URockMan** [eerimoq/asn1tools#9]
`$ asn1tools decode tests/files/foo.asn Question 300e0201011609497320312b313d333f`

Error:
```
/usr/lib/python2.7/site-packages/asn1tools/parser.py:875: SyntaxWarning: Cannot combine element of type <type 'NoneType'> with ParserElement
  + actual_parameter_list)
error: no such attribute name
```

Please guide me to solve the issue

**Comment by eerimoq** [comment]
Your pyparsing version is likely too old. Update with `pip install -U pyparsing`

**Comment by URockMan** [comment]
Thanks a lot for your reply. I have the below version installed do you want me to still update the pyparsing package.

```
$ rpm -qa | grep pyparsing
pyparsing-1.5.6-9.el7.noarch
```

**Comment by eerimoq** [comment]
It's too old. I use 2.2.0. I thought the required pyparsing version was part of setup.py, but apparently it isn't. I will add it so setuptools know about it.

**Comment by URockMan** [comment]
Thanks for your reply. Will try updating the pyparsing library.

**Comment by URockMan** [comment]
After updating the pyparsing library. It is working as expected. 
Thank you
