### ISSUE TITLE
OutOfDataError: value: out of data at bit offset 32 (4.0 bytes)

### ISSUE THREAD

**Issue by Serendipity-debug** [eerimoq/asn1tools#95]
I am decoding ENDCConfigurationUpdate massage in X2AP. The message is 39817 bytes. I know the message is very big. But asn1tools raise OutOfDataError when I decode message. How can I solve it?

**Comment by eerimoq** [comment]
X2AP is not supported as it uses classes, right? I'm surprised it even compiled.

**Comment by Serendipity-debug** [comment]
We converted the protocol given by 3gpp into a form that asn1tools can compile, such as removing the parameterization

**Comment by eerimoq** [comment]
Please create a minimal example script that reproduces the error, and I might have a look at it.

**Comment by Serendipity-debug** [comment]
Sorry, I check the mistake of code. The buffer size of sctp is too small, The data is truncated. After adding buffer size, This error does not reappear.
